when:
  - event: tag
  - event: manual

matrix:
  include:
    - TARGET: x86_64-unknown-linux-gnu
      CROSS_PKG: ""
      ENVVARS: ""
    - TARGET: aarch64-unknown-linux-gnu
      CROSS_PKG: "gcc-aarch64-linux-gnu"
      ENVVARS: "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc"
    - TARGET: x86_64-unknown-linux-musl
      CROSS_PKG: "musl-tools"
      ENVVARS: "RUSTFLAGS=-Ctarget-feature=-crt-static"
    - TARGET: aarch64-unknown-linux-musl
      CROSS_PKG: "musl-tools gcc-aarch64-linux-gnu musl-dev"
      ENVVARS: "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc RUSTFLAGS=-Ctarget-feature=-crt-static"

steps:
  - name: build
    image: hexpm/elixir:1.18.3-erlang-27.3-debian-bookworm-20250224
    commands:
      - apt-get update && apt-get install -y curl build-essential ${CROSS_PKG}
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      - rustup target add ${TARGET}
      - cd native/bz2_ex
      - ${ENVVARS} RUSTLER_NIF_VERSION=2.16 cargo build --release --target ${TARGET}