when:
  - event: deployment
    evaluate: 'CI_PIPELINE_DEPLOY_TARGET == "release"'

matrix:
  include:
    - TARGET: x86_64-unknown-linux-gnu
      CROSS_PKG: ""
      ENVVARS: ""
    - TARGET: aarch64-unknown-linux-gnu
      CROSS_PKG: "gcc-aarch64-linux-gnu"
      ENVVARS: "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc"
    - TARGET: x86_64-unknown-linux-musl
      CROSS_PKG: "musl-tools"
      ENVVARS: "RUSTFLAGS=-Ctarget-feature=-crt-static"
    - TARGET: aarch64-unknown-linux-musl
      CROSS_PKG: "musl-tools gcc-aarch64-linux-gnu musl-dev"
      ENVVARS: "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc RUSTFLAGS=-Ctarget-feature=-crt-static"

steps:
  - name: build
    image: hexpm/elixir:1.18.3-erlang-27.3-debian-bookworm-20250224
    commands:
      - apt-get update && apt-get install -y curl build-essential ${CROSS_PKG}
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      - rustup target add ${TARGET}
      - cd native/bz2_ex
      - ${ENVVARS} RUSTLER_NIF_VERSION=2.16 cargo build --release --target ${TARGET}
      - mkdir -p ../../artifacts
      - cp target/${TARGET}/release/libbz2_ex.so ../../artifacts/

  - name: package-and-upload
    image: debian:bookworm-slim
    environment:
      GITHUB_PAT_TOKEN:
        from_secret: github-pat-token
    commands:
      - apt-get update && apt-get install -y curl jq
      - cd artifacts
      - VERSION=${VERSION:-${CI_COMMIT_TAG#v}}
      - TARBALL="libbz2_ex-nif-2.16-${TARGET}-${VERSION}.tar.gz"
      - tar -czf "$TARBALL" libbz2_ex.so
      - sha256sum "$TARBALL" > "$TARBALL.sha256"
      - |
        # Get or create release
        RELEASE=$(curl -s -H "Authorization: token $GITHUB_PAT_TOKEN" \
          "https://api.github.com/repos/${CI_REPO}/releases/tags/v${VERSION}")
        UPLOAD_URL=$(echo "$RELEASE" | jq -r '.upload_url' | sed 's/{.*//')
        
        if [ "$UPLOAD_URL" = "null" ] || [ -z "$UPLOAD_URL" ]; then
          RELEASE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_PAT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"v${VERSION}\",\"name\":\"v${VERSION}\",\"draft\":false,\"prerelease\":false}" \
            "https://api.github.com/repos/${CI_REPO}/releases")
          UPLOAD_URL=$(echo "$RELEASE" | jq -r '.upload_url' | sed 's/{.*//')
        fi
        
        for file in *.tar.gz *.sha256; do
          curl -s -X POST \
            -H "Authorization: token $GITHUB_PAT_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$file" \
            "${UPLOAD_URL}?name=$file"
        done