when:
  - event: tag
  - event: manual

steps:
  - name: build-x86_64-unknown-linux-gnu
    image: rust:latest
    depends_on: []
    commands:
      - rustup target add x86_64-unknown-linux-gnu || true
      - cd native/bz2_ex
      - RUSTLER_NIF_VERSION=2.16 cargo build --release --target x86_64-unknown-linux-gnu

  - name: build-aarch64-unknown-linux-gnu
    image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main
    depends_on: []
    commands:
      - rustup target add aarch64-unknown-linux-gnu || true
      - cd native/bz2_ex
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc RUSTLER_NIF_VERSION=2.16 cargo build --release --target aarch64-unknown-linux-gnu

  - name: build-x86_64-unknown-linux-musl
    image: ghcr.io/cross-rs/x86_64-unknown-linux-musl:main
    depends_on: []
    commands:
      - rustup target add x86_64-unknown-linux-musl || true
      - cd native/bz2_ex
      - RUSTFLAGS="-C target-feature=-crt-static" RUSTLER_NIF_VERSION=2.16 cargo build --release --target x86_64-unknown-linux-musl

  - name: build-aarch64-unknown-linux-musl
    image: ghcr.io/cross-rs/aarch64-unknown-linux-musl:main
    depends_on: []
    commands:
      - rustup target add aarch64-unknown-linux-musl || true
      - cd native/bz2_ex
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc RUSTFLAGS="-C target-feature=-crt-static" RUSTLER_NIF_VERSION=2.16 cargo build --release --target aarch64-unknown-linux-musl

  - name: build-darwin
    image: docker:cli
    depends_on: []
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
    commands:
      - |
        cat > /tmp/Dockerfile.darwin << 'EOF'
        FROM crazymax/osxcross:latest AS osxcross
        FROM rust:latest AS builder
        RUN apt-get update && apt-get install -y clang lld
        COPY --from=osxcross /osxcross /osxcross
        ENV PATH="/osxcross/bin:$PATH"
        ENV LD_LIBRARY_PATH="/osxcross/lib:$LD_LIBRARY_PATH"
        WORKDIR /build
        COPY native/bz2_ex /build/native/bz2_ex
        RUN rustup target add x86_64-apple-darwin aarch64-apple-darwin
        RUN cd native/bz2_ex && \
            CC=o64-clang CXX=o64-clang++ \
            CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=o64-clang \
            cargo build --release --target x86_64-apple-darwin
        RUN cd native/bz2_ex && \
            CC=oa64-clang CXX=oa64-clang++ \
            CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=oa64-clang \
            cargo build --release --target aarch64-apple-darwin
        FROM scratch AS export
        COPY --from=builder /build/native/bz2_ex/target/x86_64-apple-darwin/release/libbz2_ex.dylib /x86_64-apple-darwin/
        COPY --from=builder /build/native/bz2_ex/target/aarch64-apple-darwin/release/libbz2_ex.dylib /aarch64-apple-darwin/
        EOF
      - docker build -f /tmp/Dockerfile.darwin -o artifacts/darwin .